//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GESTION_PLANES_COBRO
    {
        public int ID_PLAN_COBRO { get; set; }
        public int ID_RESIDENTE { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public decimal MONTO { get; set; }
        public string FRECUENCIA_COBRO { get; set; }
        public string ESTADO_COBRO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
       
    }
    
}
