//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENCIA
    {
        public int ID_INCIDENCIA { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_ESTADO_INCIDENCIA { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
    
        public virtual ESTADO_INCIDENCIA ESTADO_INCIDENCIA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
