//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CONDOMINIOSEntities : DbContext
    {
        public CONDOMINIOSEntities()
            : base("name=CONDOMINIOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AREA_COMUN> AREA_COMUN { get; set; }
        public virtual DbSet<ESTADO_DEUDA> ESTADO_DEUDA { get; set; }
        public virtual DbSet<ESTADO_INCIDENCIA> ESTADO_INCIDENCIA { get; set; }
        public virtual DbSet<ESTADO_RESERVACION> ESTADO_RESERVACION { get; set; }
        public virtual DbSet<ESTADO_RESIDENCIA> ESTADO_RESIDENCIA { get; set; }
        public virtual DbSet<ESTADO_USUARIO> ESTADO_USUARIO { get; set; }
        public virtual DbSet<GESTION_DEUDA> GESTION_DEUDA { get; set; }
        public virtual DbSet<GESTION_PLANES_COBRO> GESTION_PLANES_COBRO { get; set; }
        public virtual DbSet<INCIDENCIA> INCIDENCIA { get; set; }
        public virtual DbSet<NOTICIA> NOTICIA { get; set; }
        public virtual DbSet<PLAN_COBRO> PLAN_COBRO { get; set; }
        public virtual DbSet<REPORTES> REPORTES { get; set; }
        public virtual DbSet<RESERVA_AREA_COMUN> RESERVA_AREA_COMUN { get; set; }
        public virtual DbSet<RESERVACION> RESERVACION { get; set; }
        public virtual DbSet<RESIDENCIA> RESIDENCIA { get; set; }
        public virtual DbSet<RUBRO_COBRO> RUBRO_COBRO { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIPO_NOTICIA> TIPO_NOTICIA { get; set; }
        public virtual DbSet<TIPO_REPORTE> TIPO_REPORTE { get; set; }
        public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
