//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CONDOMINIOSEntities : DbContext
    {
        public CONDOMINIOSEntities()
            : base("name=CONDOMINIOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AREA_COMUN> AREA_COMUN { get; set; }
        public virtual DbSet<ESTADO_DEUDA> ESTADO_DEUDA { get; set; }
        public virtual DbSet<ESTADO_INCIDENCIA> ESTADO_INCIDENCIA { get; set; }
        public virtual DbSet<ESTADO_RESERVACION> ESTADO_RESERVACION { get; set; }
        public virtual DbSet<ESTADO_RESIDENCIA> ESTADO_RESIDENCIA { get; set; }
        public virtual DbSet<ESTADO_USUARIO> ESTADO_USUARIO { get; set; }
        public virtual DbSet<GESTION_DEUDA> GESTION_DEUDA { get; set; }
        public virtual DbSet<GESTION_PLANES_COBRO> GESTION_PLANES_COBRO { get; set; }
        public virtual DbSet<INCIDENCIA> INCIDENCIAs { get; set; }
        public virtual DbSet<NOTICIA> NOTICIAs { get; set; }
        public virtual DbSet<PLAN_COBRO> PLAN_COBRO { get; set; }
        public virtual DbSet<REPORTE> REPORTES { get; set; }
        public virtual DbSet<RESERVA_AREA_COMUN> RESERVA_AREA_COMUN { get; set; }
        public virtual DbSet<RESERVACION> RESERVACIONs { get; set; }
        public virtual DbSet<RESIDENCIA> RESIDENCIAs { get; set; }
        public virtual DbSet<RUBRO_COBRO> RUBRO_COBRO { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TIPO_NOTICIA> TIPO_NOTICIA { get; set; }
        public virtual DbSet<TIPO_REPORTE> TIPO_REPORTE { get; set; }
        public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    }
}
