//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICIA
    {
        public int ID_NOTICIA { get; set; }
        public string TITULO { get; set; }
        public string CONTENIDO { get; set; }
        public System.DateTime FECHA_PUBLICACION { get; set; }
    
        public virtual TIPO_NOTICIA TIPO_NOTICIA { get; set; }
    }
}
