//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTES
    {
        public int ID_REPORTE { get; set; }
        public int ID_USUARIO { get; set; }
        public int report_type_id { get; set; }
        public System.DateTime report_date { get; set; }
        public string report_data { get; set; }
    
        public virtual TIPO_REPORTE TIPO_REPORTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
