//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTES
    {
        public int ID_REPORTE { get; set; }
        public int ID_USUARIO { get; set; }
        public int report_type_id { get; set; }
        public System.DateTime report_date { get; set; }
        public string report_data { get; set; }
    
        public virtual TIPO_REPORTE TIPO_REPORTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
