//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA_AREA_COMUN
    {
        public int ID_RESERVA_AREA_COMUN { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_AREA_COMUN { get; set; }
        public System.DateTime FECHA_RESERVA { get; set; }
        public System.DateTime HORA_INICIO { get; set; }
        public System.DateTime HORA_FIN { get; set; }
        public int ID_ESTADO_RESERVACION { get; set; }
        public string COMENTARIOS { get; set; }
    
        public virtual AREA_COMUN AREA_COMUN { get; set; }
        public virtual ESTADO_RESERVACION ESTADO_RESERVACION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
