//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVACION
    {
        public int ID_RESERVACION { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_AREA_COMUN { get; set; }
        public int ID_ESTADO_RESERVACION { get; set; }
        public System.DateTime FECHA_RESERVACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public System.DateTime FECHA_FIN_RESERVACION { get; set; }
    
        public virtual AREA_COMUN AREA_COMUN { get; set; }
        public virtual ESTADO_RESERVACION ESTADO_RESERVACION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
