//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVACION
    {
        public int ID_RESERVACION { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_AREA_COMUN { get; set; }
        public int ID_ESTADO_RESERVACION { get; set; }
        public System.DateTime FECHA_RESERVACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public System.DateTime FECHA_FIN_RESERVACION { get; set; }
    
        public virtual AREA_COMUN AREA_COMUN { get; set; }
        public virtual ESTADO_RESERVACION ESTADO_RESERVACION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
