//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_REPORTE
    {
        public int TIPO_REPORTE_ID { get; set; }
        public string NOMBRE_REPORTE { get; set; }
        public string DESCRIPCIÓN_REPORTE { get; set; }
    
        public virtual REPORTES REPORTES { get; set; }
    }
}
